
name: lint

on: push

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v2

      # Runs the Super-Linter action
        uses: actions/setup-node@v1
        with: node-version: 13
        run: make lint
